### ISSUE TITLE
您好，我在运行测试代码时始终报错

### ISSUE THREAD

**Issue by hello-jo** [JunweiZheng93/APES#6]
您好，我在CVPR中看到您的论文工作，并对此非常感兴趣，但本人为刚开始接触点云的深度学习方面算法。目前通过租用的GPU训练好模型之后，下载到本地Windows系统笔记本pycharm中。在运行test.py代码时，始终报错为：KeyError: 'APESVisualizer is not in the mmengine::visualizer registry. Please check whether the value of `APESVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'。在租用的GPU上运行test.py代码无此问题，但那个界面为jupyter，无法进行测试结果可视化。还是想在本地笔记本上进行测试，我相信已经将test.py的配置环境正确，此问题已困扰数天无法解决。可能此问题仅为设置方面错误，但属实难以正确运行。如若方便，还请您帮忙解决该困惑，万分感谢，期待回复。

**Comment by hard0806** [comment]
您好，我也遇到了和您相同的问题，方便请教一下，您是怎么解决的吗？

**Comment by YBUZYX** [comment]
Dear Professor Wu, hello. I am very interested in your Attention Based Point Cloud Edge Sampling paper published on CVPR recently. Could you take the time to share the code in the CategoryMeanIoU class amidst your busy schedule? Looking forward to your early reply! Wishing you good health and a thriving career!
